/**
 * The bundled catalog snapshot (generated by `npm run build:catalog` from the
 * app's asset files), indexed once per isolate.
 */
import catalogJson from './generated/catalog.json'
import { createCatalogIndex, type CatalogData, type CatalogIndex } from '../../src/core/catalog'

let index: CatalogIndex | undefined

export function getCatalog(): CatalogIndex {
  index ??= createCatalogIndex(catalogJson as unknown as CatalogData)
  return index
}
