import { test, expect } from '@playwright/test'
import { waitForAppReady, navigateToTab } from './helpers'

test('preview batch import, preserve duplicate scripts, export JSON and filter characters', async ({ page }) => {
  await waitForAppReady(page)
  await navigateToTab(page, /剧本|Scripts/)
  await page.getByRole('button', { name: '导入剧本', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.locator('input[type=file]').setInputFiles([
    { name: 'library-test.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify([{ id: '_meta', name: 'Library Test' }, 'chef', 'imp'])) },
    { name: 'library-test.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify([{ id: '_meta', name: 'Library Second' }, 'monk'])) },
    { name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"hello":"world"}') },
  ])
  await expect(dialog.getByText('不是有效的剧本 JSON；需要角色列表。')).toBeVisible()
  await expect(page.locator('.MuiDialog-container')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: test.info().outputPath('script-import.png'), animations: 'disabled' })
  await dialog.getByRole('button', { name: '确认导入 (2)' }).click()
  await expect(dialog).not.toBeVisible()
  await page.screenshot({ path: test.info().outputPath('script-library.png') })
  await page.getByRole('button', { name: '导出 / 分享', exact: true }).click()
  await expect(page.getByRole('dialog').getByText('导出 / 分享 · Library Test')).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载 JSON · 可再次导入编辑' }).click()
  expect((await download).suggestedFilename()).toBe('Library_Test.json')
  await navigateToTab(page, /全部角色|All Characters/)
  const picker = page.getByRole('combobox', { name: '按剧本筛选角色' })
  await picker.fill('library-test')
  await expect(page.getByRole('option')).toHaveCount(2)
  await page.getByRole('option').filter({ hasText: 'Library Test' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button').filter({ hasText: 'chef ·' })).toBeVisible()
  await expect(page.getByRole('button').filter({ hasText: 'imp ·' })).toBeVisible()
  await expect(page.getByRole('button').filter({ hasText: 'monk ·' })).toHaveCount(0)
  await picker.fill('library-test-2')
  await page.getByRole('option').filter({ hasText: 'Library Second' }).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button').filter({ hasText: 'monk ·' })).toBeVisible()
  await page.getByRole('button', { name: '恶魔', exact: true }).click()
  await expect(page.getByRole('button').filter({ hasText: 'chef ·' })).toHaveCount(0)
  await expect(page.getByRole('button').filter({ hasText: 'imp ·' })).toBeVisible()
  await page.getByRole('button', { name: '恶魔', exact: true }).click()
  await page.getByRole('textbox', { name: /按名称、ID 或能力搜索|Search/ }).fill('no-such-character-123')
  await expect(page.getByText('没有符合当前条件的角色')).toBeVisible()
  await page.getByRole('button', { name: '清空全部筛选', exact: true }).first().click()
  await expect(page.getByText('没有符合当前条件的角色')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
  await page.screenshot({ path: test.info().outputPath('character-library.png') })
})

test('secondary controls stay accessible without duplicate primary actions', async ({ page }) => {
  await waitForAppReady(page)
  await navigateToTab(page, /剧本|Scripts/)
  await expect(page.getByRole('button', { name: '新建剧本', exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: '导入剧本', exact: true })).toHaveCount(1)
  await expect(page.getByRole('button', { name: '切换到卡片视图' })).toHaveCount(0)
  await page.getByRole('button', { name: '显示设置', exact: true }).click()
  await page.getByRole('combobox', { name: '剧本浏览方式' }).click()
  await page.getByRole('option', { name: '卡片', exact: true }).click()
  await expect(page.getByRole('button', { name: '导出 / 分享', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '显示设置', exact: true }).click()
  await page.getByRole('combobox', { name: '剧本浏览方式' }).click()
  await page.getByRole('option', { name: '列表', exact: true }).click()
  await expect(page.getByRole('button', { name: '导出 / 分享', exact: true })).toBeVisible()
  if (await page.getByRole('button', { name: '选择剧本', exact: true }).isVisible()) {
    await page.getByRole('button', { name: '选择剧本', exact: true }).click()
    await expect(page.getByRole('button', { name: '导出 / 分享', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: /^黯月初升/ }).first().click()
    await expect(page.getByRole('button', { name: '导出 / 分享', exact: true })).toBeVisible()
  }
  await page.screenshot({ path: test.info().outputPath('scripts-refined.png'), animations: 'disabled' })
  await navigateToTab(page, /全部角色|All Characters/)
  await expect(page.getByRole('button', { name: '清空全部筛选', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await expect(page.getByRole('button', { name: '导入角色包', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await page.getByRole('button', { name: '角色工具', exact: true }).click()
  const tools = page.getByRole('dialog')
  await expect(tools.getByRole('button', { name: '导入单个角色', exact: true })).toBeVisible()
  await expect(tools.getByText('角色包管理')).toBeVisible()
  await expect(tools.getByText('规则与顺序')).toBeVisible()
  await tools.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '剧本来源' })).not.toBeVisible()
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '剧本来源' })).toBeVisible()
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await page.screenshot({ path: test.info().outputPath('characters-refined.png'), animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
})

test('script navigation filters sources and manages copies and folders', async ({ page }) => {
  await waitForAppReady(page)
  await navigateToTab(page, /剧本|Scripts/)
  const choose = page.getByRole('button', { name: '选择剧本', exact: true })
  if (await choose.isVisible()) await choose.click()
  const nav = page.getByRole('navigation', { name: '剧本导航' })
  await nav.getByRole('button', { name: /^官方 3$/ }).click()
  await expect(nav.getByRole('button', { name: /^更多操作:/ })).toHaveCount(3)
  await expect(nav.getByText('还没有自己的剧本，可以新建或复制现有剧本。')).toHaveCount(0)
  await nav.getByRole('button', { name: /^更多操作:/ }).first().click()
  await expect(page.getByRole('menuitem', { name: '删除', exact: true })).toHaveCount(0)
  await page.getByRole('menuitem', { name: /复制/ }).click()
  await expect(nav.getByRole('button', { name: /^我的 1$/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(nav.getByRole('button', { name: /^更多操作:/ })).toHaveCount(1)
  await nav.getByRole('button', { name: '管理', exact: true }).click()
  await page.getByRole('menuitem', { name: '管理文件夹', exact: true }).click()
  const manager = page.getByRole('dialog')
  await manager.getByRole('textbox', { name: '新建文件夹', exact: true }).fill('周末剧本')
  await manager.getByRole('button', { name: '新建文件夹', exact: true }).click()
  await manager.getByRole('button', { name: '关闭', exact: true }).click()
  await nav.getByRole('button', { name: /^更多操作:/ }).click()
  await page.getByRole('menuitem', { name: /移动/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: '周末剧本', exact: true }).click()
  await nav.getByRole('combobox', { name: '剧本文件夹', exact: true }).fill('周末')
  await page.getByRole('option', { name: '周末剧本', exact: true }).click()
  await expect(nav.getByRole('button', { name: /^更多操作:/ })).toHaveCount(1)
  await nav.getByRole('button', { name: '清空全部筛选', exact: true }).click()
  await nav.getByRole('combobox', { name: /^排序/ }).click()
  await page.getByRole('option', { name: /角色数量|角色数/ }).click()
  await expect(nav.getByRole('button', { pressed: true }).filter({ hasText: /个角色/ })).toHaveCount(1)
  await page.screenshot({ path: test.info().outputPath('script-navigation.png'), animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBeTruthy()
})
