/**
 * Portable snapshot of the bundled catalog (characters, jinxes, night order,
 * scripts, editions), generated by scripts/build-catalog.mjs from the same
 * asset files the web app loads. Runtimes without Vite (the API worker, Node
 * tools) read this instead of src/catalog.ts. User overrides (custom
 * characters, revision/jinx edits) are not included — this is the canonical
 * data only.
 */
import type { Team } from '../types/catalog'

export type Localized = { en: string; zh: string }

export type CatalogCharacter = {
  id: string
  team: Team
  edition: string
  /** Display name per language, with the same cross-language fallback as the app. */
  name: Localized
  /** Current ability text per language, with the same fallback as the app. */
  ability: Localized
  /** Flavor text (official characters, mostly English only). */
  flavor?: Partial<Localized>
  /** Reminder tokens per language (falls back to the other language, then the language-neutral list). */
  reminders: { en: string[]; zh: string[] }
  remindersGlobal: { en: string[]; zh: string[] }
  setup?: boolean
  firstNightReminder?: Partial<Localized>
  otherNightReminder?: Partial<Localized>
  /** 1-based position in the global first-night / other-night order, when the character wakes. */
  firstNight?: number
  otherNight?: number
  /** Icon file name under assets/icons, when one exists. */
  icon?: string
}

export type CatalogJinx = {
  id: string
  characters: [string, string]
  status: 'active' | 'inactive'
  reason: Localized
}

export type CatalogScript = {
  slug: string
  sourceFile: string
  /** The script exactly as bundled (official array format or legacy object). */
  data: unknown
}

export type CatalogEdition = {
  id: string
  name: Localized
  author?: Partial<Localized>
  source?: string
  /** Fan-made (民间) pack, not an official release. */
  community?: boolean
}

export type CatalogData = {
  version: 1
  generatedAt: string
  characters: CatalogCharacter[]
  jinxes: CatalogJinx[]
  /** Global wake order, including placeholders such as DUSK / MINION_INFO / DAWN. */
  nightOrder: { first: string[]; other: string[] }
  scripts: CatalogScript[]
  editions: CatalogEdition[]
}
