/**
 * Check a model's answer before showing it (docs/AI-ARCHITECTURE-OFFLINE-FIRST.md
 * §5 "验证并展示"): when the question asked for a game line-up or a script,
 * the characters the answer gives are checked against the rules. If they are
 * missing or not legal, the program's legal line-up / script is appended with
 * the reason — models explain well but often miscount.
 */
import { getDisplayName } from '../../catalog'
import { charactersIn, listLine, poolProblems, setupProblems } from './answerParse'
import { planRequest } from './ruleFacts'
import type { AiContext } from './types'

export type CheckedAnswer = { text: string; corrected: boolean }

const names = (ids: string[], zh: boolean) => `${ids.join(', ')}（${ids.map((id) => getDisplayName(id, zh ? 'zh' : 'en')).join(zh ? '、' : ', ')}）`

export function checkAnswer(ctx: Pick<AiContext, 'language' | 'characterIds' | 'seats'>, query: string, text: string): CheckedAnswer {
  const request = planRequest(query, ctx)
  if (!request) return { text, corrected: false }
  const zh = ctx.language === 'zh'
  const label = zh ? '程序校验' : 'Program check'

  if (request.kind === 'setup') {
    const { plan, script, players } = request
    if (!plan || plan.inPlay.length !== players) return { text, corrected: false }
    // An explicit list line, or else exactly the script characters the answer names.
    const named = [...charactersIn(text)].filter((id) => script.includes(id))
    const ids = listLine(text, ['在场角色', 'Characters in play']) ?? (named.length === players ? named : null)
    const problems = ids ? setupProblems(ids, script, players, ctx.language) : []
    if (ids && !problems.length) return { text, corrected: false }
    const why = ids
      ? (zh ? `回答里的配置不符合规则（${problems.join('；')}）` : `the line-up in the answer breaks the rules (${problems.join('; ')})`)
      : (zh ? '回答里没有完整的在场角色名单' : 'the answer has no complete list of characters in play')
    const bluffs = plan.bluffs.length ? `\n${zh ? '恶魔伪装' : 'Demon bluffs'}: ${names(plan.bluffs, zh)}` : ''
    return {
      corrected: true,
      text: `${text}\n\n---\n**${label}**：${why}。${zh ? '以下是程序生成的一套合法配置：' : 'A legal line-up generated by program:'}\n${zh ? '在场角色' : 'Characters in play'}: ${names(plan.inPlay, zh)}${bluffs}`,
    }
  }

  const { pool, requirements } = request
  const ids = listLine(text, ['剧本角色', 'Script characters'])
  const problems = ids ? poolProblems(ids, requirements, ctx.language) : []
  if (ids && !problems.length) return { text, corrected: false }
  const why = ids
    ? (zh ? `回答里的剧本不符合要求（${problems.join('；')}）` : `the script in the answer does not meet the request (${problems.join('; ')})`)
    : (zh ? '回答里没有完整的剧本角色名单' : 'the answer has no complete list of script characters')
  return {
    corrected: true,
    text: `${text}\n\n---\n**${label}**：${why}。${zh ? '以下是程序按要求组出的合法剧本（角色池）：' : 'A legal script (character pool) built by program:'}\n${zh ? '剧本角色' : 'Script characters'}: ${names(pool.characters, zh)}`,
  }
}
